### ISSUE TITLE
Fix the cards

### ISSUE THREAD

**Issue by mishrashree18** [zairza-cetb/Heart-to-Heart-Frontend#1]
![Screenshot from 2022-10-03 15-46-22](https://user-images.githubusercontent.com/65803594/193554263-0abb88d4-5cbf-4eda-8fc8-977f2e3d145a.png)

1. Add hover effects (like scale up) to the cards and the buttons on it.

![Screenshot from 2022-10-03 15-48-53](https://user-images.githubusercontent.com/65803594/193554633-01be4da8-c389-4bac-91f1-5b255b2cbca1.png)

2. For smaller screens, make the cards of same size and eliminate the bug that is shown in the picture (cards being of different sizes)

**Comment by Utkarsh212** [comment]
Would you please assign this to me so I can start working on it?

**Comment by mishrashree18** [comment]
> Would you please assign this to me so I can start working on it?

assigned 👍🏼 @Utkarsh212 start working

**Comment by Utkarsh212** [comment]
#7

**Comment by Utkarsh212** [comment]
@mishrashree18 I have submitted PR: #7. Please review It.

**Comment by mishrashree18** [comment]
done
