### ISSUE TITLE
Enhance the footer section

### ISSUE THREAD

**Issue by mishrashree18** [zairza-cetb/Heart-to-Heart-Frontend#2]
![Screenshot from 2022-10-03 15-51-28](https://user-images.githubusercontent.com/65803594/193555150-f11e65f4-cb76-475c-a5da-244d63ab7165.png)

1. Make the font size more prominient
2. Improve the UI based on your creativity

**Comment by Ns-SheF** [comment]
Hi....  am I suppose to fork this repo or ask to be assigned to the issue first? Not sure how it works

**Comment by mishrashree18** [comment]
You can fork the repo and run the project to check if you can work on this issue, and ask it to be assigned to you

**Comment by Ns-SheF** [comment]
Okay

**Comment by amanchoudhary18** [comment]
I can work on this issue. Assign it to me.

**Comment by mishrashree18** [comment]
> I can work on this issue. Assign it to me.

assigned 👍🏼 start working @amanchoudhary18

**Comment by amanchoudhary18** [comment]
Can u check the pull request

**Comment by mishrashree18** [comment]
done
