### ISSUE TITLE
Fix the Vector in the Feedback section

### ISSUE THREAD

**Issue by mishrashree18** [zairza-cetb/Heart-to-Heart-Frontend#3]
![Screenshot from 2022-10-03 15-53-25](https://user-images.githubusercontent.com/65803594/193555488-512e455f-8882-477e-b8de-47c113cea157.png)

As of now, for smaller screens the vector on the left does not properly occupy the desired space and is of the desired size. Fix that bug.

**Comment by Utkarsh212** [comment]
Please assign this issue to me so I can work on it.

**Comment by mishrashree18** [comment]
> Please assign this issue to me so I can work on it.

@Utkarsh212 I have assigned you the issue. You can start working on it

**Comment by Utkarsh212** [comment]
Fixed this issue in PR: #8

**Comment by Utkarsh212** [comment]
@mishrashree18 I have submitted PR: #8. Please review It.

**Comment by mishrashree18** [comment]
done
